### ISSUE TITLE
Support RedisClient in addition to Redis gem

### ISSUE THREAD

**Issue by HarlemSquirrel** [lbeder/health-monitor-rails#107]
Right now the Redis check assumes we are using the `Redis` gem. However, [Sidekiq 7](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#redis-client) now uses [RedisClient](https://github.com/redis-rb/redis-client). It would be great to be able to use either gem for the Redis check.

In the mean time, I have built a an interface to allow not including the Redis gem in a Rails app: https://gist.github.com/HarlemSquirrel/b5af94f603144ae1fc0c8aec702dce29

**Comment by lbeder** [comment]
Hey @HarlemSquirrel,
Thanks for the insight! I wasn't aware that [Sidekiq 7](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md#redis-client) is now using [RedisClient](https://github.com/redis-rb/redis-client).

Could you try to configure the Redis provider to work with a custom connection? I've added an example (which is very similar to your gist) to the tests here: https://github.com/lbeder/health-monitor-rails/blob/06323a170c35c122592e0c18b9729470c043539f/spec/lib/health_monitor/providers/redis_spec.rb#L72

**Comment by HarlemSquirrel** [comment]
Ah nice yeah that should work. We did find that we do actually still need Redis gem for now.

**Comment by lbeder** [comment]
Glad that it worked! 😄

**Comment by tmobaird** [comment]
Ran into a similar issue, worked around it by adding a custom redis client and implementing, `#info`, `#get` and `#set` using RedisClient methods.

```ruby
class CustomRedisClient
  attr_reader :client

  def initialize
    @client = RedisClient.new(url: ENV["REDIS_URL"])
  end

  def info
    @client.call("INFO", "used_memory")
  end

  def get(key)
    @client.call("GET", key)
  end

  def set(key, time)
    @client.call("SET", key, time)
  end
end

HealthMonitor.configure do |config|
  config.path = 'readyz'
  config.redis
  config.redis.configuration.connection = CustomRedisClient.new
end
```

Hope it helps! Open to feedback if useful to anyone else.

**Comment by lbeder** [comment]
If the issue is mostly with Sidekiq 7, perhaps it's sufficient to only check Sidekiq and avoid an extra check for its underlying Redis provider?
