### ISSUE TITLE
💡 Use own styling instead Tailwind

### ISSUE THREAD

**Issue by loed-idzinga** [lbeder/health-monitor-rails#109]
Would it be an idea to not include Tailwind, but add own custom styling? 

This way we can prevent loading Tailwind as a dependency, but also reduce the need to set CSP headers.

An optional idea is to make this styling configurable.

**Comment by lbeder** [comment]
I think this is a good idea and a great opportunity to contribute to this gem 👍

**Comment by loed-idzinga** [comment]
Awesome! I'll come back to this 👍
