### ISSUE TITLE
DB Provider doesn't detect a dropped DB connection (ie. killing the db)

### ISSUE THREAD

**Issue by jayceekay** [lbeder/health-monitor-rails#117]
I'm not sure if this is meant to be detected but I noticed that when I manually stop the db, ie. by killing the process or stopping the container, the default DB provider doesn't detect it. You can see that here on my local (you might have to pop out the GIF to see the text, and I'm not sure why this gif is so fast - I can recreate it if we need a slower version):

![health-monitor](https://github.com/lbeder/health-monitor-rails/assets/1119866/73d0ee9a-599f-422a-ac20-1460081abc08)

Using docker compose I've repro'd it here: https://github.com/jayceekay/health-monitor-repro. Just run `docker compose up`, `docker ps` to find the postgres container, then `docker stop [sha-for-postgres]` to bring down the DB

**Comment by lbeder** [comment]
Thanks for reporting this and providing such a cool reproduction @jayceekay. I wanted to switch to the "SELECT 1" method for a while and it seems that due to newer cp caching - the time is better than ever 😅
