### ISSUE TITLE
Make sidekiq maximum_amount_of_retries configurable

### ISSUE THREAD

**Issue by hackartisan** [lbeder/health-monitor-rails#119]
This is a feature request. Thank you for this gem, we're getting great use out of it!

Relevant code: https://github.com/lbeder/health-monitor-rails/blob/d828b9cb0c8fb6fb7f358d8feb39ab080ef03f23/lib/health_monitor/providers/sidekiq.rb#L99

**Comment by lbeder** [comment]
Thanks for the great suggest @hackartisan

**Comment by hackartisan** [comment]
Nice, thank you!!
