### ISSUE TITLE
database check doesn't work for mongoid, and can't be turned off

### ISSUE THREAD

**Issue by jesmith17** [lbeder/health-monitor-rails#12]
Rails 5 app using mongoid for the DB. The current database check doesn't work for mongoid. I plan to work on a PR to add a mongoid check, but my issue is that because the database check is on by default and the check fails mongoid, my health check always fails. 

I think having the database check by default makes sense, but we need a way to disable it if needed. 

Tried to creating a new "database" check to see if it would override it in the list, but that simply produces 2 DB checks.

**Comment by lbeder** [comment]
That's a very valid point. I'll come up with a solution in the next couple of days (i.e., either a way to disable the default db check or to generalize the check to handle mongodb as well).

**Comment by lbeder** [comment]
I've added the `config.no_database` optional method (see README.md) and release a new version of the gem. Thanks for the feedback! 👍
