### ISSUE TITLE
Health.json error only if specifically filtered to

### ISSUE THREAD

**Issue by tpendragon** [lbeder/health-monitor-rails#126]
My use case is I have some datadog checks that rely on `health.json?providers[]=sidekiq` returning a 503, but I want to mark that service as non-critical for the root `health.json` so I can use that in my load balancer. I have a patch that accomplishes what I want here: https://github.com/pulibrary/figgy/pull/6534, but I'm curious if there's some form of that which might be useful in the context of the gem as a whole?

I'm not sure what would make the most sense, because just including it would be a pretty serious breaking change. Maybe a third critical option, or another parameter that says ignore_critical?

**Comment by lbeder** [comment]
I'd consider instead creating your own Sidekiq custom provider and handling its errors according to your specific app logic
