### ISSUE TITLE
Add HTML status page

### ISSUE THREAD

**Issue by n-rodriguez** [lbeder/health-monitor-rails#14]
It would be nice to have an HTML view of the status page like https://github.com/rails-engine/status-page (actually a fork of your gem)

**Comment by lbeder** [comment]
Yeah, I agree. It'd be a wonderful addition, but unfortunatelly I don't think I'd have the time to do it any time soon. Perhaps @rails-engine would consider contributing the HTML status back here as well.

**Comment by n-rodriguez** [comment]
I can do a PR if you want, the fork doesn't seem to be maintained any more.
By the way, is the Redis provider configurable?

**Comment by lbeder** [comment]
That'd be great! I'd be help however I can.

The redis provider isn't configurable, since it's calling `Redis.new` (i.e., assumes that you've already initialized/configured your redis provider). What do you think that is currently missing?

**Comment by n-rodriguez** [comment]
> The redis provider isn't configurable, since it's calling Redis.new (i.e., assumes that you've already initialized/configured your redis provider). What do you think that is currently missing?

Nothing, I didn't know Redis.new would reused an already configured Redis session.

**Comment by lbeder** [comment]
Ah, it'll only reuse its configuration, if you've initialized your Redis provider in an initializer (which is almost always the case). Of course, if you see a possibility for improvement / additional configuration - I'd be more than happy to add it.

**Comment by lbeder** [comment]
(Sorry, closed it accidentally)

**Comment by n-rodriguez** [comment]
Done : https://github.com/lbeder/health-monitor-rails/pull/15 :)
