### ISSUE TITLE
Monitoring script

### ISSUE THREAD

**Issue by n-rodriguez** [lbeder/health-monitor-rails#17]
I've got a Ruby script ready to eat `health-monitor-rails` json output.
It's compatible with Nagios / Shinken / Icinga / Icinga2.
Would you like a PR to add it in a `contrib` or `extra` directory?

**Comment by lbeder** [comment]
Sounds great, thanks! :+1:

**Comment by n-rodriguez** [comment]
Done : https://github.com/lbeder/health-monitor-rails/pull/18
