### ISSUE TITLE
Looking to add "Warnings" along with errors...

### ISSUE THREAD

**Issue by toastytheog** [lbeder/health-monitor-rails#20]
Looking to add "Warnings" along with errors for the latency of sidekiq, but the test in this line is holding me back. This doesn't test for an actual failure for sidekiq, just confirms that sidekiq isn't configured.
https://github.com/lbeder/health-monitor-rails/blob/master/spec/lib/health_monitor/monitor_spec.rb#L152

**Comment by lbeder** [comment]
Hey @toastytheog, I'm not sure I understand. The line above stubs `allow_any_instance_of(Sidekiq::Workers).to receive(:size).and_raise(Exception)` and tests a general sidekiq error (in this case, that there is communication error). There is also another stub for latency.

Could you elaborate what exactly you're trying to achieve?

**Comment by toastytheog** [comment]
I want two thresholds for latency for sidekiq, and possibly other providers. One threshold for a yellow light, and one for a panic light. I've committed some code into my forked branch if you want to take a look at how I'm approaching it. https://github.com/toastytheog/health-monitor-rails/commit/a67cf52a0566d1969ab9f09a5bb7a200354575f2

**Comment by lbeder** [comment]
So why is the test holding you back? You're more than welcome to modify it according to your changes. I've went over your code and it's a good direction, but will require some prior modification, if you'd like to submit a PR.

**Comment by toastytheog** [comment]
I guess my main issue is my unfamiliarity with tests in general. I'm not sure how this specific project sets up the configurations to show that sidekiq is enabled, and the current test only provides the response for DB and Redis on the 'sidekiq fails' check. I was expecting to see:

`            :results => [
              {
                name: 'Database',
                message: '',
                status: 'OK'
              },
              {
                name: 'Redis',
                message: '',
                status: 'OK'
              },
              {
                name: 'Sidekiq',
                message: 'Some Failure Message',
                status: 'Failed'
              }
            ],
`

**Comment by toastytheog** [comment]
NVM, I'm dumb, it was in an earlier test.           
`subject.configure do |config|
            config.database
            config.redis
            config.sidekiq
          end`
