### ISSUE TITLE
Help with configuring

### ISSUE THREAD

**Issue by stuartweir** [lbeder/health-monitor-rails#25]
Hi there!

This looks like an excellent library for what I want to do, I just have a couple questions.

1. Where do I add the HealthMonitor.configure block? does that go in `routes.rb`?
2. How can I add custom `messages` to different settings, such as if the database is unavailable, or redis is non-responsive?
3. For basic auth, is it possible to use an API key token instead? If not, would I have to pass the user/pass in the URI request, such as `testsite.com/check?user=USER?password=PASSWORD`?

Thanks for the help!

-Stu

**Comment by lbeder** [comment]
Hi @stuartweir,

re: 1 - it should be initialized during the start of the application, which is usually under the `initializers` folder. Placing it in `routes.rb` will also work, but not very common. 

re: 2 - at the moment, this is not supported. Can you describe a use case for such a feature?

re: 3 - no, this handler is specifically for HTTP Basic Authentication protocol.

**Comment by stuartweir** [comment]
Hey @lbeder, thanks so much for your speedy response!

re: 1 - thank you, will do that!

re: 2 - I suppose in the case where we want a specific message when the DB is unavailable (this data gets fed into DataDog, eventually) we might want something a bit more tailored than the default message (even if the default is fine)

re: 3 - thank you for clarifying!

-Stu

**Comment by lbeder** [comment]
re: 2 - I'll try to add this feature to the next release.
