### ISSUE TITLE
Sidekiq reading OK when inactive 

### ISSUE THREAD

**Issue by noto-alex-j** [lbeder/health-monitor-rails#26]
Hi!

Excellent gem you have here. I actually stumbled upon it from rails-engine/status-page. I was planning to use status-page; however, it looks like health-monitor-rails has been a little better maintained. I was testing them side by side and noticed that when I shut down my Sidekiq instance, status-page reports an error with Sidekiq not having any active instances, while health-monitor-rails continues to report OK. A cursory glance at the sidekiq.rb files between the two shows that status-page raises an error when processes.size == 0, while health-monitor-rails does not.

Two questions: 
What should health-monitor-rails display when Sidekiq is not enabled?
What, if any, other differences are there between the two gems? 

Thanks!

**Comment by lbeder** [comment]
Thanks for the kind words.

The `status-page` project was a fork from this project, so I can't really tell what are the differences at the moment. AFAIK, this project is more configurable and is still being actively maintained. 

I agree with your observation and will add `processes.size == 0` check as well.

**Comment by lbeder** [comment]
Fixed and released as [7.3.0](https://github.com/lbeder/health-monitor-rails/releases/tag/v7.3.0).
