### ISSUE TITLE
Redis client is nil

### ISSUE THREAD

**Issue by sveredyuk** [lbeder/health-monitor-rails#28]
My configuration as:
```ruby
HealthMonitor.configure do |config|
  config.database
  config.cache
  config.sidekiq
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.latency = 1.minute
  end

  config.redis
  if ENV['REDIS_URL']
    config.redis.configure do |redis_config|
      redis_config.url = ENV['REDIS_URL']
    end
  end
end
```

Brings redis error:
`undefined method `client' for nil:NilClass`

In development environment i use local redis, but for staging and production I extract redis url from ENV.

<img width="1001" alt="2017-12-22 11 57 13" src="https://user-images.githubusercontent.com/5221643/34293982-48e45214-e70f-11e7-9df0-fe8862ea3e1e.png">

**Comment by lbeder** [comment]
Could you check if it still happens on 7.3.1?

**Comment by sveredyuk** [comment]
Updated gem and catch another one for Redis:
`undefined method `close' for nil:NilClass Did you mean? clone`

**Comment by lbeder** [comment]
Weird... it doesn't reproduce neither here nor during the tests. Can you upload your Gemfile and Gemfile.lock? Perhaps it's something to do with some of the gems you're using.

Can you also remove the redundant `config.redis` call and see if it helps in this case?

**Comment by sveredyuk** [comment]
my Gemfile is too heavy ( Maybe it's all about my Redis connection.
My app use always Redis.current instead Redis.new. Maybe I can contribute new config attribute to redis?

**Comment by lbeder** [comment]
You mean, something like `: current` bool property? If it helps, then by
all means. Any contribution is welcome, just make sure to update the tests
and the documentation accordingly.

**Comment by sveredyuk** [comment]
@lbeder debug shows configuration is nil inside check! redis instance just not creating and ensure redis.close raising exception... hmmm

**Comment by lbeder** [comment]
It means that redis creation fails in your case, for some reason...

If you could reproduce it on a separate app - I'd be happy to help you
debugging it.

**Comment by sveredyuk** [comment]
Ok... MR on the way

**Comment by sveredyuk** [comment]
How I could fix pull request pipeline? Test coverage show me decreasing by 0.3%.. but I cannot find where I can check what exactly my pr miss to cover? 

P.S. Hate this coverall UI

**Comment by lbeder** [comment]
It looks like your PR has some style violations. You can run `rake rubocop` to see the errors or check the status from Travis CI.

Let me know if you're planning to submit the 2nd PR re: redis memory check and then I'd test and merge them both, once everything works.

**Comment by sveredyuk** [comment]
Pushed commit with rubocop fixes already.

**Comment by sveredyuk** [comment]
And yes, next one will be for check redis memory usage.

**Comment by sveredyuk** [comment]
Also added queues_size for Sidekiq check. By default 100 jobs.
