### ISSUE TITLE
Feature Thoughts?

### ISSUE THREAD

**Issue by orangewolf** [lbeder/health-monitor-rails#35]
Hi, we've been evaluating the various health page engines and think that health-monitor-rails is probably the best platform to build on.  We're looking at adding the following features and were curious which ones we should try and contribute back and which you'd prefer us to keep in our own fork.

- Print git version to verify that the release is correct (similar to Envylabs Rapporteur https://github.com/envylabs/rapporteur)
- Elasticsearch
- Solr
- Delayed Job (PR already in place)

**Comment by rmm5t** [comment]
Just sitting on the sidelines here, but I for one would like to see a built-in elasticsearch provider

**Comment by lbeder** [comment]
They all sound great. I agree that Delayed Job support could've been very helpful (I'll merge the PR soon), as well as support for Elasticsearch. Printing git version also sounds pretty cool :D

**Comment by orangewolf** [comment]
One more for you - we want to add a route that always fails. We'd use this to test 500 pages, to see that exception tracking is working, etc. It wouldn't be on the main page, but a separate child route. I can write a custom rule for it, but I don't think I want to add an even to Sentry every 5 minutes when I ping the server.

**Comment by lbeder** [comment]
Hmmm... I think that the 500 pages suggestion isn't appropriate for the project, since it's focused on provided health endpoints for various health querying services, and an always failing endpoint doesn't fit this philosophy. But your other ideas are golden!
