### ISSUE TITLE
Always HTTP 200?

### ISSUE THREAD

**Issue by rmm5t** [lbeder/health-monitor-rails#38]
The response code for the health check pages always returns an `HTTP 200` success code even if one of the providers fails its health check.

This surprised me. I expected a `500` error if one of the underlying providers had an error. Same body response, but a different response code.

Thoughts?

**Comment by lbeder** [comment]
Sounds to me like a bug which was introduced when the HTML status page was added. Would you like to give it a shot?

**Comment by rmm5t** [comment]
> Sounds to me like a bug which was introduced when the HTML status page was added.

😬

> Would you like to give it a shot?

Maybe if I have time later, but sorry 😞, I already switched to the `okcomputer` gem instead, because it behaves as expected. Given that this gem was on v7, and given that specs were part of the project, I made the assumption that 200 response codes were some sort of design decision, but for me (and all systems I've ever built) that obviously defeats the purpose of a health monitor endpoint.

**Comment by lbeder** [comment]
Thanks for pointing this out, in any case. I've fixed this in: https://github.com/lbeder/health-monitor-rails/pull/39. Once the tests will pass, I'll release as 8.0.0 (since the change is backwards incompatible).
