### ISSUE TITLE
Redis & Sidekiq nil:NilClass errors

### ISSUE THREAD

**Issue by MiralDesai** [lbeder/health-monitor-rails#40]
I've got both Redis and Sidekiq running, I can access sidekiq via my rails applications, however both of the items on the health check page return an error.

For Sidekiq the error is: `undefined method 'latency' for nil:NilClass`

For Redis the error is: `undefined method 'connection' for nil:NilClass`

Both are definitely running. Via the console I can get the latency on a queue, without any issues. The same goes for Redis, I can call `Redis.current.connection` and it works just fine. So not sure why it fails for the health check page.

**Comment by lbeder** [comment]
Hi @MiralDesai,
Could you share your initialization code or even a small demo app that reproduces this issue? It'd be very helpful in understanding the issue you're having.

**Comment by MiralDesai** [comment]
Hey,

Here's my initializer:

```
HealthMonitor.configure do |config|
  # config.no_database To turn off database check
  config.cache
  config.sidekiq
  config.redis
  config.add_custom_provider(::Check::Custom1)
  config.add_custom_provider(::Check::Custom1)
  config.add_custom_provider(::Check::Custom3)
end
```

**Comment by lbeder** [comment]
Can you try to eliminate the duplicate `config.add_custom_provider(::Check::Custom1)`?

**Comment by MiralDesai** [comment]
Sorry that was just me copying it incorrectly. Have edited my post.

**Comment by lbeder** [comment]
Could you try to remove the custom providers and see if it works? Perhaps they are modifying the configuration instance in some way (which is the error that you're getting).

**Comment by MiralDesai** [comment]
I've removed the custom providers, and still getting the same issue.

Can confirm both `Sidekiq::Queue.new.latency` and `Redis.current.connection` return results from rails console.

**Comment by lbeder** [comment]
Can you add the whole stack trace of the exception? I want to be sure if it's a configuration or provider issue.

**Comment by MiralDesai** [comment]
How do I go about getting the full stacktrace? Still learning RoR. It's not showing in our logs. 

This is the only thing that appears in the logs:

```
Started GET "/check" for 127.0.0.1 at 2018-06-12 17:00:14 +0100
   (1.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by HealthMonitor::HealthController#check as HTML
  CACHE  (0.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  Rendering /Users/mdesa7/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/health-monitor-rails-8.1.0/app/views/health_monitor/health/check.html.erb
  Rendered /Users/mdesa7/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/health-monitor-rails-8.1.0/app/views/health_monitor/health/check.html.erb (1.6ms)
Completed 200 OK in 48ms (Views: 27.4ms | ActiveRecord: 0.7ms)
```

**Comment by lbeder** [comment]
I mean, the full trace of where you see the `undefined method 'latency' for nil:NilClass` error message.

**Comment by lbeder** [comment]
Maybe you're using some old versions of either redis or sidekiq? It's very hard for me to help you, without a way to reproduce this issue. Similar scenarios works for everyone else (and of course all the test pass). If you'd be able to come up with a sample app which reproduces it - I'd be able to quickly sort it out.

**Comment by lbeder** [comment]
Recreating the provider isn't enough, since we not that it's supposed to work (e.g., the tests and other users of this library). There is something very specific that's wrong in your setup and without reproducing it - it'd be very hard to understand what's wrong. 

Maybe you call the initializer before setting up Sidekiq or Redis?
