### ISSUE TITLE
Feature idea / File system permissions

### ISSUE THREAD

**Issue by danielnc** [lbeder/health-monitor-rails#42]
We have a pretty complex set of rails apps & workers that run on top of a kubernetes cluster

We need to know if certain file system folders are writable/readable from the rails app, so nginx containers, rails & Sidekiq can read/write files to those locations.

Read/Write monitor is something that you believe makes sense to add to the health-monitor-rails core or should be dealt with as a custom monitor?

I am glad to work on this, just don't want to add this and get a rejected PR 👍

**Comment by lbeder** [comment]
I think it's a great idea and can be implemented as a `FileSystemProvider`, but of course would have to be mindful of security considerations. Thank you so much for the contribution! :)
