### ISSUE TITLE
Sidekiq configuration in README is misleading

### ISSUE THREAD

**Issue by legendetm** [lbeder/health-monitor-rails#48]
When I configured the Sidekiq monitoring according to README example, then I was hitting the default limits. It seems, that Sidekiq montoring internally uses queue and following changes does NOT change the queue settings. 
```
# Sidekiq
HealthMonitor.configure do |config|
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.latency = 3.hours
    sidekiq_config.queue_size = 50
  end
end
```

It seems that the other example updates queue correctly, but the method signature is wrong, `size` should be `queue_size`
```
# To configure specific queues
HealthMonitor.configure do |config|
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.add_queue_configuration("critical", latency: 10.seconds, size: 20)
  end
end
```

**Comment by legendetm** [comment]
Please see the code `https://github.com/lbeder/health-monitor-rails/blob/master/lib/health_monitor/providers/sidekiq.rb` from there you see, that only `configuration.queues` is used, and default queue is configured with default values, not with user given values.

After setting the former code, the configuration is 
```
HealthMonitor.configure do |config|
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.latency = 3.hours
    sidekiq_config.queue_size = 50
  end
end

HealthMonitor.configuration.providers.to_a[1].new(request: nil).configuration
#<HealthMonitor::Providers::Sidekiq::Configuration:0x00007ff8f2eb2128 @queue_name="default", @latency=3 hours, @queue_size=50, @queues={"default"=>{:latency=>30, :queue_size=>100}}>
```
The Sidekiq configuration has correct values, but the queue uses default values.

**Comment by lbeder** [comment]
Ah, gotcha! Fix is on its way.

**Comment by legendetm** [comment]
That was fast 👍

**Comment by lbeder** [comment]
Fix and released at https://github.com/lbeder/health-monitor-rails/releases/tag/v8.5.0.

Thanks again for bringing it up!
