### ISSUE TITLE
undefined method 'configure' for HealthMonitor:Module

### ISSUE THREAD

**Issue by andrewsage** [lbeder/health-monitor-rails#58]
For my initializers/health_monitor.rb 

```
Rails.application.config.after_initialize do
	HealthMonitor.configure do |config|
  	config.basic_auth_credentials = {
    	username: 'SECRET_NAME',
    	password: 'Shhhhh!!!'
  	}
  end
end
```

I'm getting the following error:

`config/initializers/health_monitor.rb:2:in `block in <top (required)>': undefined method `configure' for HealthMonitor:Module (NoMethodError)`

**Comment by lbeder** [comment]
Hmmm... it could be related to Rails 4.2's autoloading. Can you check if adding `require 'health_monitor/engine'` solves this?

**Comment by andrewsage** [comment]
I've added the require in and I'm still getting the error.

**Comment by lbeder** [comment]
Could you verify that you're using `8.6.2` (and not `8.6.0`, where a similar issue could have happen)?

**Comment by andrewsage** [comment]
Thanks it is working now. It was still running 8.6.0.

**Comment by lbeder** [comment]
Thanks for verifying it.
