### ISSUE TITLE
Can't login redis with password auth only

### ISSUE THREAD

**Issue by Doltair** [lbeder/health-monitor-rails#63]
Hello!,

Good day! this gem is really helpful, however i am currently facing issues connecting redis with password only auth:

<img width="1028" alt="Screen Shot 2019-09-23 at 11 01 43 PM" src="https://user-images.githubusercontent.com/15558671/65437419-579d6f80-de56-11e9-8b78-cb433a044da0.png">

Anyhow, Sidekiq returns "Error" if redis is down which is great, that indicates there's a connection issue. 

What is the correct settings for config.redis_url? I followed the instructions in README markdown but it won't work still says *NO AUTH. Authentication required*

Running Redis 5 >, sidekiq 6

**Comment by lbeder** [comment]
Thanks for the kind words. 

Could you perhaps share how are you configuring your `redit_url`? Perhaps you are somehow overriding it with a URL without authentication info?

**Comment by Doltair** [comment]
Hi @lbeder, 

Welcome! as requested, here's my sidekiq.rb under initializes settings:
```
sidekiq_config = { url: ENV['REDIS_URL'], password: ENV['REDIS_PASSWORD'], network_timeout: 15 } 

Sidekiq.configure_server do |config|
  config.redis = sidekiq_config
end

Sidekiq.configure_client do |config|
  config.redis = sidekiq_config
end
```

While for Health monitor, I am trying the instructions from Readme markdown:

```
HealthMonitor.configure do |config|
  config.cache
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.latency = 3.hours
    sidekiq_config.queue_size = 20
  end
  config.redis.configure do |redis_config|
  redis_config.connection = Redis.current # use your custom redis connection
  # redis_config.url = "ENV[REDIS_URL]" <=== *im going to use Environment / ENV moving forward   to not expose the creds*
  redis_config.url = 'redis://:redispassword@example.redis.com:6379/0
  redis_config.max_used_memory = 200 # Megabytes
  end
end
```

**Comment by lbeder** [comment]
Ah, the issue is that you can't use both `redis_config.connection` and `redis_config.url` at the same time. Using `redis_config.connection` overrides `redis_config.url`. The documentation is a bit confusing (there is an "or" there, but it's very easy to miss out). Could you verify that using `redis_config.url` does the trick and then I'll update the documentation accordingly?

**Comment by lbeder** [comment]
Hey @Doltair, any news?

**Comment by Doltair** [comment]
Hi @lbeder

My apologies, for the late response i just comeback and ran the test again , anyhow yes! that works!

<img width="1176" alt="Screen Shot 2019-09-25 at 8 19 24 PM" src="https://user-images.githubusercontent.com/15558671/65600022-ceab4300-dfd1-11e9-924c-98434b88b201.png">

```
  config.redis.configure do |redis_config|
#  redis_config.connection = Redis.current # use your custom redis connection
  redis_config.url = "redis://:redispassword@redismaster:6379/0"
```

**Comment by lbeder** [comment]
Thanks for verifying it. I'll update the documentation to make this more clear.

**Comment by Doltair** [comment]
Cool! and Welcome! 

Thank you too for the support! Really appreciate it.
