### ISSUE TITLE
HealthMonitor::Providers::SidekiqException · undefined method `queues' for nil:NilClass

### ISSUE THREAD

**Issue by CodyMcMichael** [lbeder/health-monitor-rails#70]
I ran into a weird issue where sidekiq was throwing this error. `HealthMonitor::Providers::SidekiqException · undefined method `queues' for nil:NilClass`

This was my config.

```ruby
HealthMonitor.configure do |config|
  config.cache
  config.sidekiq

  config.error_callback = proc do |error|
    Rails.logger.error "Health check failed with: #{error.message}"

    Bugsnag.notify error do |report|
      report.severity = 'error'
    end
  end
end
```

However, if I update my config to use a latency, even the default, then it passes just fine. Any thoughts?

```ruby
HealthMonitor.configure do |config|
  config.cache
  config.sidekiq
  config.sidekiq.configure do |sidekiq_config|
    sidekiq_config.latency = 30
  end

  config.error_callback = proc do |error|
    Rails.logger.error "Health check failed with: #{error.message}"

    Bugsnag.notify error do |report|
      report.severity = 'error'
    end
  end
end
```

![image](https://user-images.githubusercontent.com/22300402/90437175-88524d00-e097-11ea-8706-28be5ff0bf7e.png)

**Comment by lbeder** [comment]
It could be the result of using this gem with a no longer support `2.2.0` ruby version. Can you try (only as a test) with `2.5.8` (or later) and see if it helps?

**Comment by CodyMcMichael** [comment]
@lbeder thanks for the reply. I have a suspicion that's the issue as well. Unfortunately I can't make that big of a jump right now without going through crazy dependency hell. Do you foresee any issues with the way I Have it set up in the mean time, manually adding in the latency config?

**Comment by lbeder** [comment]
There shouldn't be any issues with the way you've configured it (other than some redundancy, which is understandable in this case).

**Comment by dmitrym0** [comment]
FWIW, this error still occurs with `ruby 3.1.1p18`. The work around works too.
