### ISSUE TITLE
Sidekiq - Queue nil error

### ISSUE THREAD

**Issue by vanhecke** [lbeder/health-monitor-rails#89]
Thanks for sharing this gem.

I encounter an issue with the sidekiq check. I receive the following error in the status page.
```
ERROR
undefined method `queues' for nil:NilClass configuration.queues.each do |queue, config| ^^^^^^^
```

When I manually define the queues to monitor, the problem goes away:

```
sidekiq_config.add_queue_configuration("critical", latency: 10.seconds, queue_size: 20)
sidekiq_config.add_queue_configuration("low", latency: 10.seconds, queue_size: 20)
```

Based on the readme I thought it would work ootb without the specific queue definition.

```
Versions
Ruby    3.1.0
Sidekiq 6.4.1
Rails   7.0.3
```

**Comment by lbeder** [comment]
I'm unable to reproduce it. Any chance you could set up a small demo project with reproduction and then I'd be able to debug the issue and fix it?
