### ISSUE TITLE
Support a connection pool for Redis

### ISSUE THREAD

**Issue by HarlemSquirrel** [lbeder/health-monitor-rails#90]
Redis now recommends using a [connection pool ](https://github.com/mperham/connection_pool)so it would be great to have support for that here.

We should then not need to close connections as the connection pool should handle all of this for us.

I wrote small wrapper class that makes my Rails app work with the existing Redis check.

```rb
class RedisPoolClientHelper
  def close; end

  def get(key)
    pool.with { |c| c.get(key) }
  end

  def set(key, value)
    pool.with { |c| c.set(key, value) }
  end

  private

  def pool
    REDIS_CONNECTION_POOL # This is defined in my redis initializer
  end
end

# config/initializers/health-monitor.rb
Rails.application.config.after_initialize do
  HealthMonitor.configure do |config|
      config.redis.configure do |redis_config|
        redis_config.connection = RedisPoolClientHelper.new
      end
    end
end
   
```

**Comment by lbeder** [comment]
Hey @HarlemSquirrel,
This is definitely a neat idea. I'll absolutely add it soon. Thanks! 👍

**Comment by lbeder** [comment]
@HarlemSquirrel please check #92. It's now possible to configure the redis provider by providing a connection pool directly (+ it's not using a connection pool internally as well)
