### ISSUE TITLE
Gem correct working with Memcached?

### ISSUE THREAD

**Issue by d4mk0** [lbeder/health-monitor-rails#93]
Hi.
When we drop our memcache server
check.json responds what it is ok.
```json
    {
      "name": "Cache",
      "message": "",
      "status": "OK"
    }
```

It is correct behaviour? Or maybe not?
Any advices for correct watch status of memcache? Thank u.

**Comment by lbeder** [comment]
Hi @d4mk0,
It's possible that you have a fallback to the default cache provider in case your memcached server is down? Basically, the cache check is performed by caching a key (via `Rails.cache.write`) and reading it back (via `Rails.cache.read`) which seems to pass in your case.
